/*!
This is automatically generated file. 
DO NOT EDIT THIS FILE. 
@author		Shun Moriya 
@copyright 2024 Shun Moriya All Rights Reserved.
*/
#pragma once
#if !defined(TITLEMANAGER_PLUGIN_INFOMATION_DETECTED)
#define TITLEMANAGER_PLUGIN_INFOMATION_DETECTED
#define TITLEMANAGER_PLUGIN_FILE_VERSION 3
#define TITLEMANAGER_PLUGIN_VERSION 1
#define TITLEMANAGER_PLUGIN_VERSION_NAME "1.0"
#define TITLEMANAGER_PLUGIN_FRIENDLY_NAME "TitleManager"
#define TITLEMANAGER_PLUGIN_DESCRIPTION "Keeps track of the proficiency level of each tool and the experience level of the tool's category."
#define TITLEMANAGER_PLUGIN_DOCS_URL "https://github.com/shun126/TitleManager/wiki"
#define TITLEMANAGER_PLUGIN_SUPPORT_URL "https://github.com/shun126/TitleManager/discussions"
#define TITLEMANAGER_PLUGIN_BETA_VERSION false
#endif
