/* 
This is automatically generated file. 
DO NOT EDIT THIS FILE. 
\author		Shun Moriya 
\copyright	2024- Shun Moriya 
All Rights Reserved. 
*/ 
#pragma once 
#if !defined(JENKINS_BUILD_DETECTED) 
#define JENKINS_BUILD_DETECTED 
#define JENKINS_BUILD_NUMBER 0
#define JENKINS_BUILD_ID 0
#define JENKINS_NODE_NAME "" 
#define JENKINS_JOB_NAME "TitleManagerPlugin" 
#define JENKINS_BUILD_TAG "" 
#define JENKINS_JOB_TAG "" 
#define JENKINS_GIT_BRANCH "" 
#define JENKINS_GIT_COMMIT "" 
#define JENKINS_UUID "6f42f8ff-77a9-4f75-3928-a159972d8dec" 
#define JENKINS_LICENSE "MIT" 
#define JENKINS_FOR_DEVELOP 1 
#define JENKINS_FOR_RELEASE 0 
#endif 
